stages:
  get_data:
    cmd: python ./saved_models/src/get_data.py --config=params.yaml
    deps:
    - ./saved_models/src/get_data.py
    - ./data_given/data_file_lab.csv
    outs:
    - ./data/processed/data.csv

  load_data:
    cmd: python ./saved_models/src/load_data.py --config=params.yaml
    deps:
    - ./saved_models/src/get_data.py
    - ./saved_models/src/load_data.py
    - ./data_given/data_file_lab.csv
    outs:
    - ./data/raw/data_file_lab.csv

  split_data:
    cmd: python ./saved_models/src/split_data.py --config=params.yaml
    deps:
    - ./saved_models/src/split_data.py
    - ./data/raw/data_file_lab.csv
    outs:
    - ./data/processed/x_train.csv
    - ./data/processed/y_train.csv
    - ./data/processed/x_test.csv 
    - ./data/processed/y_test.csv
#, dvc plots show
  train_and_evaluate:
    cmd: python  ./saved_models/src/train_and_evaluate.py --config=params.yaml 
    
    deps:
    - ./data/processed/x_train.csv
    - ./data/processed/y_train.csv
    - ./data/processed/x_test.csv 
    - ./data/processed/y_test.csv
    - ./saved_models/src/train_and_evaluate.py
    
    metrics:
    - report/scores.json:
        cache: false

    # plots:
      
    # - report/prc.json:
    #     cache: false
    #     x: recall
    #     y: precision
    # - report/roc.json:
    #     cache: false
    #     x: fpr
    #     y: tpr
    # - cm.csv:
    #     cache: false
        

    outs:
    - ./saved_models/model.joblib