base:
  project: dvc_tutorial
  random_state: 999
  target_col: chd

data_source:
  source: ./data_given/data_file_lab.csv

load_data:
  raw_dataset_csv: ./data/raw/data_file_lab.csv

split_data:
  x_train_path: ./data/processed/x_train.csv
  y_train_path: ./data/processed/y_train.csv
  x_test_path: ./data/processed/x_test.csv
  y_test_path: ./data/processed/y_test.csv
  test_size: 0.2
  
model_dir: saved_models

reports:
  scores: report/scores.json
  # roc: report/roc.json
  # prc: report/prc.json
  # auc: report/auc.json